ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.makebleja.ApplicationKt.module ]
    }
}
postgres {
  url = ${?DB_URL}
  user = ${?DB_USER}
  password = ${?DB_PASSWORD}
}
email {
  user = ${?EMAIL_USER}
  password = ${?EMAIL_PASS}
}
jwt {
    domain = "https://jwt-provider-domain/"
    audience = "jwt-audience"
    realm = "ktor sample app"
}
